# Generated by Django 4.2.4 on 2023-10-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0004_rename_user_subscription_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='User',
            new_name='user',
        ),
    ]
