# Generated by Django 4.2.4 on 2023-10-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0009_remove_category_subscribers_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='User',
            new_name='user',
        ),
    ]
