# Generated by Django 4.2.4 on 2023-11-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0012_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='category name', max_length=100),
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinds', to='simpleapp.category', verbose_name='This is the help text')),
            ],
        ),
    ]
